[feat] Api Customers
MatheusPitschWarren/API_Customers pull request #1
Opened 2022-09-13 17:07 UTC by MatheusPitschWarren

[.NET] 01 - Back-End Criação do usuário

2022-09-13 17:16 UTC, viniciusoliveira-warren commented on Data/Data.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
```suggestion
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
```

2022-09-13 17:17 UTC, viniciusoliveira-warren commented on Data/Model/BaseModel.cs
> +    public class BaseModel
Nunca vamos instanciar essa classe, deve ser marcada como abstract pois é usada apenas para extensão
```suggestion
    public abstract class BaseModel
```

2022-09-13 17:17 UTC, viniciusoliveira-warren commented on Data/Model/BaseModel.cs
> +        public int Id { get; set; }
long porque dependendo da tabela pode ter dados "infinitos"
```suggestion
        public long Id { get; set; }
```

2022-09-13 17:17 UTC, viniciusoliveira-warren commented on Data/Validator/CustomerValidator.cs
> +        public CustomerValidator()
```suggestion
    {
        public CustomerValidator()
```

2022-09-13 17:20 UTC, ghost reviewed
Adicionar .gitignore para arquivos .vs, bin e obj e deletar arquivos referentes a estas pastas que estão na branch

2022-09-14 13:36 UTC, ghost commented on WebApiCustomers/Controllers/CustomersController.cs
> +    [Route("Api/[controller]")]
```suggestion
namespace WebApiCustomers.Controllers
{
    [Route("Api/[controller]")]
```

2022-09-14 13:38 UTC, viniciusoliveira-warren commented on WebApiCustomers/WebApiCustomers.csproj
> +  </ItemGroup>
Deletar pasta NovaPasta

2022-09-14 13:38 UTC, viniciusoliveira-warren commented on WebApiCustomers/WebApiCustomers.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
```suggestion
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.2" />
```

2022-09-14 19:07 UTC, LeonardoAlthoff requested changes
Revisar comentários

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/Repository/BaseRepository.cs
> +        public virtual CustomersModel GetById(long id)
Como esta classe é a implementação do IBaseRepository, as funções dela não devem ter o "virtual"
```suggestion
        public CustomersModel GetById(long id)
```

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/Controllers/CustomersController.cs
> +        }
A função que está sendo chamada retorna um customer ou nulo (FirstOrDefault). Assim, o repositório deve enviar dois tipos diferentes de resposta: 200 (Ok) para caso encontre ou 404 (NotFound) para retorno nulo.

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/Repository/BaseRepository.cs
> +            model.Cpf = model.Cpf.Trim().Replace(".", "").Replace("-", "");
Como o card pede para salvar o cpf sem os pontos e outros caracteres, é interessante passar essa função diretamente no constutor do CustomerModel. Assim, não haverá necessidade de char a função em outros lugares e você garantirá que o atributo está no formato requerido.

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/Repository/BaseRepository.cs
> +
As validações devem ser realizadas de modo automático. É necessário especificar isso na classe program.cs e, após isso, excluir as instanciações e validações manuais.

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/Repository/BaseRepository.cs
> +            return 400;
Ao invés de realizar essa verificação manualmente, é preferível realizar a verificação com o método Any.
```suggestion
                if(_customersList.Any(customer => customer.Cpf == model.Cpf || customer.Email == model.Email) return 409
                _customerList.Add(model);
                return 201;
```

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/Repository/BaseRepository.cs
> +            model.Cpf = model.Cpf.Trim().Replace(".", "").Replace("-", "");
Vide comentário anterior.

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/Repository/BaseRepository.cs
> +            return 404;
Realizar a verificação com o Any(), como no exemplo anterior. Desse modo será mais performático, pois retornará apenas um boolean, ao invés de um Customer.

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/Controllers/CustomersController.cs
> +            }
Não há necessidade de colocar o "else" nessas funções. Caso o código entre no if, ele deixará de percorrer o restante da função após o "return". Outra coisa,  se ocorre algum erro, é interessante especificar na resposta qual foi ele.

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/Validator/CustomerValidator.cs
> +                    .WithMessage("Full name must not be null or empty");
O método NotEmpty() já abarca o NotNull. Assim, não há necessidade de colocar os dois.

2022-09-14 19:07 UTC, LeonardoAlthoff commented on WebApiCustomers/WeatherForecast.cs
> +}
Apagar.
```suggestion

```

2022-09-16 17:53 UTC, AlanmWarren commented on WebApiCustomers/Controllers/CustomersController.cs
> +
```suggestion
            return BadRequest("There is already a customer with this CPF and Email ");
```
Linhas em branco e seria mais correto retornar BadRequest

2022-09-16 17:55 UTC, AlanmWarren commented on WebApiCustomers/Controllers/CustomersController.cs
> +        }
```suggestion
        public IActionResult Post(CustomersModel model)
        {
            var response = _repository.Create(model);

            if (response == 201)
            {
                return Created("", response);
            }
            return BadRequest("There is already a customer with this CPF and Email ");
        }
```
Cuidar com as linhas em branco desnecessárias e seria melhor retornar BadRequest

2022-09-19 16:41 UTC, AlanMDomingues commented on WebApiCustomers/Repository/BaseRepository.cs
> +    public class BaseRepository : IBaseRepository
```suggestion
    public class CustomerService: ICustomerService
```

2022-09-19 16:41 UTC, AlanMDomingues commented on WebApiCustomers/Repository/IBaseRepository.cs
> +    public interface IBaseRepository
```suggestion
    public interface ICustomerService
```

2022-09-19 16:41 UTC, AlanMDomingues commented on WebApiCustomers/Repository/BaseRepository.cs
> +namespace WebApiCustomers.Repository
```suggestion
namespace WebApiCustomers.Services
```
Alterar nome da pasta para Services

2022-09-19 16:41 UTC, AlanMDomingues commented on WebApiCustomers/Repository/BaseRepository.cs
> +            model.Id = _customersList.Count + 1;
Sua lógica de auto incrementar IDs está meio quebrada

Exemplo:
Lista com os IDs: 1, 2, 3, 4; count = 4,
Adicionar novo customer: next id = count + 1 = 5
Resultado = 1, 2, 3, 4, 5
Até aí tudo bem, irá adicionar um novo ID sem problemas

Se eu deletar um customer e depois adicionar um novo, ficará assim: (Customer deletado: id = 1)
Lista com os IDs: 2, 3, 4, 5; count = 4;
Adicionar novo customer: next id = count + 1 = 5
Resultado = 2, 3, 4, 5, 5
O ID = 5 se repete

Se eu deletar novamente um customer e depois adicionar um novo... (Customer deletado: id = 2)
Lista com os IDs: 3, 4, 5, 5; count = 4;
Adicionar novo customer: next id = count + 1 = 5
Resultado = 3, 4, 5, 5, 5
O ID = 5 se repete

Resultado Final => IDs: 3, 4, 5, 5, 5; count = 5
Não podemos repetir ID, pois é um identificador individual.

2022-09-19 16:41 UTC, AlanMDomingues commented on WebApiCustomers/Repository/BaseRepository.cs
> +            else if (_customersList.Any(customer => customer.Cpf != model.Cpf || customer.Email != model.Email))
Essa validação podemos fazer em um método separado e privado

2022-09-19 16:41 UTC, AlanMDomingues commented on WebApiCustomers/Repository/BaseRepository.cs
> +                updateModel.Id = updateModel.Id;
Isso não está fazendo nada

2022-09-19 16:41 UTC, AlanMDomingues commented on WebApiCustomers/Repository/BaseRepository.cs
> +            var customer = _customersList.Any(customer => customer.Cpf == model.Cpf || customer.Email == model.Email);
```suggestion
            var customerExists = _customersList.Any(customer => customer.Cpf == model.Cpf || customer.Email == model.Email);
```

2022-09-19 16:41 UTC, AlanMDomingues commented on WebApiCustomers/Repository/BaseRepository.cs
> +            return 404;
É mais correto usar o `if` para o caso de erro, pois o `if` será bem menor

2022-09-19 16:41 UTC, AlanMDomingues commented on WebApiCustomers/Model/CustomersModel.cs
> +        }
esse método poderia estar em uma classe como método de extensão

2022-09-19 18:10 UTC, AlanmWarren commented on WebApiCustomers/Validator/CustomerValidator.cs
> +        public CustomerValidator()
Fazer mais validações

2022-09-20 17:03 UTC, AlanmWarren commented on WebApiCustomers/Validator/CustomerValidator.cs
> +            .Length(6, 60);
`.Length()` valida apenas se o campo tiver exatamente o tamanho que foi passado no parâmetro, no caso está aceitando apenas nomes com 6 caracteres ou 60 caracteres.
O certo é usar .`MinimumLength()` e `.MaximumLength()`.
Fazer isso para as outras validações também.

2022-09-20 17:04 UTC, AlanmWarren commented on WebApiCustomers/Validator/CustomerValidator.cs
> +            .NotEmpty();
Faltou validação

2022-09-21 10:26 UTC, merged